/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import DataBase.Connect;
import DataBase.Employee;
import Proccess.LoaiSP;
import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vanli
 */
public class QuanLyDanhMucSanPham extends javax.swing.JFrame {
            LoaiSP sp = new LoaiSP();


    /**
     * Creates new form QuanLyDanhMucSanPham
     */
    public QuanLyDanhMucSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_birthday = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_fullname = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Lưu = new javax.swing.JButton();
        btn_Khong_Luu = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_quan_ly_san_pham = new javax.swing.JTable();
        lb_gender = new javax.swing.JLabel();
        txt_gender = new javax.swing.JTextField();
        txt_birthday = new javax.swing.JTextField();
        txt_adress = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        lb_email = new javax.swing.JLabel();
        lb_fullname = new javax.swing.JLabel();
        lb_adress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH MỤC LOẠI SẢN PHẨM");
        jLabel1.setMaximumSize(new java.awt.Dimension(198, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(198, 50));

        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_id.setText("Id");

        lb_birthday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_birthday.setText("Birthday");

        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Lưu.setText("Lưu");
        btn_Lưu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LưuActionPerformed(evt);
            }
        });

        btn_Khong_Luu.setText("Không Lưu");
        btn_Khong_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Khong_LuuActionPerformed(evt);
            }
        });

        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        tb_quan_ly_san_pham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Full Name", "Birthday", "Gender", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_quan_ly_san_pham);

        lb_gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_gender.setText("Gender");

        txt_gender.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_birthday.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_adress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lb_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_email.setText("Email");

        lb_fullname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_fullname.setText("Full Name");

        lb_adress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_adress.setText("Adress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(lb_id))
                                        .addComponent(lb_adress, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lb_email)
                                    .addComponent(lb_gender)
                                    .addComponent(lb_birthday)
                                    .addComponent(lb_fullname, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 191, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Them)
                .addGap(18, 18, 18)
                .addComponent(btn_Xoa)
                .addGap(18, 18, 18)
                .addComponent(btn_Sua)
                .addGap(18, 18, 18)
                .addComponent(btn_Lưu)
                .addGap(18, 18, 18)
                .addComponent(btn_Khong_Luu)
                .addGap(18, 18, 18)
                .addComponent(btn_Thoat)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_fullname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_birthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_gender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_adress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Thoat)
                    .addComponent(btn_Khong_Luu)
                    .addComponent(btn_Lưu)
                    .addComponent(btn_Sua)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_Them))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        // TODO add your handling code here:
//        this.dispose();
            System.exit(0);
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        if(txt_id.getText()== ""){
            JOptionPane.showMessageDialog(null, "Vui long nhap id sinh vien muon xoa!!!!");
        }else{
        try {
                Connection conn = Connect.getConnection();
                String sql = "DELETE FROM tbnhanvien WHERE id=?";
                CallableStatement stm = conn.prepareCall(sql);
                stm.setString(1, txt_id.getText());
                stm.execute();
                JOptionPane.showMessageDialog(this, "Đã xóa thành công nhân viên : " + txt_id.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }}
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_Khong_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Khong_LuuActionPerformed
        // TODO add your handling code here:
        try {
                Connection cnn = Connect.getConnection();
                String sql = "SELECT * FROM tbnhanvien";
                java.sql.PreparedStatement stm = cnn.prepareStatement(sql);
                ResultSet rs = stm.executeQuery();
                while (rs.next()) {
                    Employee ep = new Employee();
                    rs.getString("id");
                    rs.getString("fullname");
                    rs.getString("birthday");
                    rs.getString("gender");
                    rs.getString("email");
                    rs.getString("address");
                    JOptionPane.showMessageDialog(this, "Id nhan vien là : " + rs.getString("id")
                            + "\nTên đầy đủ : " + rs.getString("fullname")
                            + "\nNgày sinh : " + rs.getString("birthday") + "\nGiới tính : " + rs.getString("gender")
                            + "\nEmail : " + rs.getString("email")
                            + "\nĐịa Chỉ : " + rs.getString("address"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_btn_Khong_LuuActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        if(txt_id.getText() =="" && txt_adress.getText()=="" && txt_birthday.getText()=="" && txt_email.getText()=="" && txt_fullname.getText()=="" && txt_gender.getText() == ""){
            JOptionPane.showMessageDialog(null, " Vui long nhap du thong tin!!! ");
        }else{try {
                Connection conn = Connect.getConnection();
                String sql = "update tbnhanvien set fullname=?, birthday = ?, gender = ?, email = ?, address=?  where id = ?";
//                String sql = "update tbnhanvien values (?,?,?,?,?,?)";
                CallableStatement stm = conn.prepareCall(sql);
                Employee ep = new Employee();
                stm.setString(1, ep.getFullname());
                stm.setString(2, ep.getBirthday());
                stm.setString(3, ep.getGender());
                stm.setString(4, ep.getEmail());
                stm.setString(5, ep.getAddress());
                stm.setInt(6, ep.getId());
                stm.executeUpdate();
                ResultSet rs = stm.getGeneratedKeys();
                JOptionPane.showMessageDialog(this,"Sửa thành công " + ep.getId());
            } catch (SQLException Ex) {
                JOptionPane.showMessageDialog(this, Ex);
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        if(txt_id.getText() =="" && txt_adress.getText()=="" && txt_birthday.getText()=="" && txt_email.getText()=="" && txt_fullname.getText()=="" && txt_gender.getText() == ""){
            JOptionPane.showMessageDialog(null, " Vui long nhap du thong tin!!! ");
        }else{
        try {
                Connection conn = Connect.getConnection();
//                String sql = "insert into tbnhanvien values (null,?,?,?,?,?,?)";
                String sql = "insert into tbnhanvien(id,fullname,birthday,gender,email,address)"+ "values (?,?,?,?,?,?)";
                java.sql.PreparedStatement stm = conn.prepareCall(sql);
                Employee nhanvien = new Employee();
                stm.setString(2, nhanvien.getFullname());
                stm.setString(3, nhanvien.getBirthday());
                stm.setString(4, nhanvien.getGender());
                stm.setString(5, nhanvien.getEmail());
                stm.setString(6, nhanvien.getAddress());
                stm.setInt(1, nhanvien.getId());
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this, "Thêm thành công ID" + nhanvien.getId());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }}
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_LưuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LưuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LưuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDanhMucSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDanhMucSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDanhMucSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDanhMucSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDanhMucSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Khong_Luu;
    private javax.swing.JButton btn_Lưu;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_adress;
    private javax.swing.JLabel lb_birthday;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_fullname;
    private javax.swing.JLabel lb_gender;
    private javax.swing.JLabel lb_id;
    private javax.swing.JTable tb_quan_ly_san_pham;
    private javax.swing.JTextField txt_adress;
    private javax.swing.JTextField txt_birthday;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
