/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learn.com.form;

import com.mysql.jdbc.PreparedStatement;
//import com.sun.jndi.ldap.Connection;
import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
//import sun.applet.Main;

/**
 *
 * @author vanli
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textUser = new javax.swing.JTextField();
        textPass = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        loginbtn = new javax.swing.JButton();
        jUsername = new javax.swing.JLabel();
        jPassword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jShowbtn = new javax.swing.JButton();
        jFixbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jFullname = new javax.swing.JTextField();
        jBirthday = new javax.swing.JTextField();
        jGender = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jDellbtn = new javax.swing.JButton();
        jSearch = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textUser.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        textUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserActionPerformed(evt);
            }
        });

        textPass.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        textPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPass.setToolTipText("");
        textPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textPass.setName(""); // NOI18N
        textPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPassActionPerformed(evt);
            }
        });
        textPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPassKeyPressed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jCheckBox1.setText("Nhớ mật khẩu");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        loginbtn.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        loginbtn.setText("Đăng nhập");
        loginbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
        });
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        jUsername.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsername.setText("Username");
        jUsername.setToolTipText("");
        jUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPassword.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPassword.setText("Password");
        jPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đăng Nhập");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Chưa có tài khoản?");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jShowbtn.setText("Hiển thị");
        jShowbtn.setToolTipText("");
        jShowbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowbtnActionPerformed(evt);
            }
        });

        jFixbtn.setText("Sửa");
        jFixbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFixbtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Id");
        jLabel1.setToolTipText("");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email");
        jLabel2.setToolTipText("");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fullname");
        jLabel5.setToolTipText("");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Address");
        jLabel6.setToolTipText("");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gender");
        jLabel7.setToolTipText("");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Birthday");
        jLabel8.setToolTipText("");

        jId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jId.setText("Id");
        jId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdActionPerformed(evt);
            }
        });

        jFullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFullname.setText("Fullname");
        jFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFullnameActionPerformed(evt);
            }
        });

        jBirthday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jBirthday.setText("Birthday");
        jBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBirthdayActionPerformed(evt);
            }
        });

        jGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jGender.setText("Gender");

        jEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jEmail.setText("Email");
        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });

        jAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jAddress.setText("Address");
        jAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddressActionPerformed(evt);
            }
        });

        jDellbtn.setText("Xóa");
        jDellbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDellbtnActionPerformed(evt);
            }
        });

        jSearch.setText("Tìm Kiếm");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jAdd.setText("Thêm");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jId))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textUser, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textPass)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jShowbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jFixbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDellbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFullname)
                            .addComponent(jBirthday)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGender))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddress)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jShowbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFixbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDellbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        textPass.getAccessibleContext().setAccessibleName("t");
        jPassword.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        if (textUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui long nhap username!!!");
        } else if (textPass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui long nhap password!!!");
        } else {
            try {
                java.sql.Connection conn = learn.com.form.CSDL.getConnection();
                conn.setAutoCommit(true);
                String sql = "SELECT * FROM `tbuser` WHERE username=? AND password=?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, textUser.getText());
                pst.setString(2, textPass.getText());
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    NhanVien nhanvien = new NhanVien();
                    rs.getString("username");
                    rs.getString("password");
                    JOptionPane.showMessageDialog(this, "Dang nhap thanh cong!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Dang nhap that bai!!!");
                }
                conn.setAutoCommit(false);
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!!!");
            }
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnMouseClicked

    private void textUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserActionPerformed

    private void jShowbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowbtnActionPerformed
        // TODO add your handling code here:
        if (!"admin".equals(textUser.getText()) && !"user1".equals(textUser.getText()) && !"user2".equals(textUser.getText())) {
            JOptionPane.showMessageDialog(null, "Vui long nhap dung username!!!");
        } else if (!"123456".equals(textPass.getText())) {
            JOptionPane.showMessageDialog(null, "Vui long nhap dung password!!!");
        } else {
            try {
                Connection cnn = learn.com.form.CSDL.getConnection();
                String sql = "SELECT * FROM tbnhanvien";
                java.sql.PreparedStatement stm = cnn.prepareStatement(sql);
                ResultSet rs = stm.executeQuery();
                while (rs.next()) {
                    NhanVien nhanvien = new NhanVien();
                    rs.getString("id");
                    rs.getString("fullname");
                    rs.getString("birthday");
                    rs.getString("gender");
                    rs.getString("email");
                    rs.getString("address");
                    JOptionPane.showMessageDialog(this, "Id nhan vien là : " + rs.getString("id")
                            + "\nTên đầy đủ : " + rs.getString("fullname")
                            + "\nNgày sinh : " + rs.getString("birthday") + "\nGiới tính : " + rs.getString("gender")
                            + "\nEmail : " + rs.getString("email")
                            + "\nĐịa Chỉ : " + rs.getString("address"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }

    }//GEN-LAST:event_jShowbtnActionPerformed

    private void jFixbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFixbtnActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        if (!"admin".equals(textUser.getText()) && !"user1".equals(textUser.getText()) && !"user2".equals(textUser.getText())) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng username!!!");
        } else if (!"123456".equals(textPass.getText())) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng password!!!");
        } else if (jId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Id!!! ");
        } else if (jFullname.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Fullname!!! ");
        } else if (jAddress.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Address!!! ");
        } else if (jBirthday.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Birthday!!! ");
        } else if (jGender.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Gender!!! ");
        } else if (jEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Email!!! ");
        } else {
            try {
                conn = learn.com.form.CSDL.getConnection();
                String sql = "update tbnhanvien set fullname=?, birthday = ?, gender = ?, email = ?, address=?  where id = ?";
//                String sql = "update tbnhanvien values (?,?,?,?,?,?)";
                CallableStatement stm = conn.prepareCall(sql);
                NhanVien nhanvien = new NhanVien();
                stm.setString(1, nhanvien.getFullname());
                stm.setString(2, nhanvien.getBirthday());
                stm.setString(3, nhanvien.getGender());
                stm.setString(4, nhanvien.getEmail());
                stm.setString(5, nhanvien.getAddress());
                stm.setString(6, nhanvien.getId());
                stm.executeUpdate();
                ResultSet rs = stm.getGeneratedKeys();
                JOptionPane.showMessageDialog(this,"Sửa thành công " + nhanvien.getId());
            } catch (SQLException Ex) {
                JOptionPane.showMessageDialog(this, Ex);
            }
        }
    }//GEN-LAST:event_jFixbtnActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void jIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdActionPerformed

    private void jAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddressActionPerformed

    private void jBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBirthdayActionPerformed

    private void textPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPassActionPerformed

    private void jDellbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDellbtnActionPerformed
        // TODO add your handling code here:
        if (!"admin".equals(textUser.getText())&& !"user1".equals(textUser.getText()) && !"user2".equals(textUser.getText())) {
            JOptionPane.showMessageDialog(null, "Vui long nhap dung username!!!");
        } else if (!"123456".equals(textPass.getText())) {
            JOptionPane.showMessageDialog(null, "Vui long nhap dung password!!!");
        } else if (jId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Id cần xóa");
        } else {
            try {
                Connection conn = learn.com.form.CSDL.getConnection();
                String sql = "DELETE FROM tbnhanvien WHERE id=?";
                CallableStatement stm = conn.prepareCall(sql);
                stm.setString(1, jId.getText());
                stm.execute();
                JOptionPane.showMessageDialog(this, "Đã xóa thành công nhân viên : " + jId.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jDellbtnActionPerformed

    private void jFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFullnameActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
        if (!"admin".equals(textUser.getText())&& !"user1".equals(textUser.getText()) && !"user2".equals(textUser.getText())) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập username!!!");
        } else if (!"123456".equals(textPass.getText())) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập password!!!");
        } else {
            try {
                Connection conn = learn.com.form.CSDL.getConnection();
                String sql = "SELECT * FROM tbnhanvien WHERE id LIKE ?";
                java.sql.PreparedStatement stm = conn.prepareStatement(sql);
                stm.setString(1, jId.getText());
                ResultSet rs = stm.executeQuery();
                if (rs.next()) {
                    NhanVien nhanvien = new NhanVien();
                    nhanvien.setId(rs.getString("id"));
                    nhanvien.setFullname(rs.getString("fullname"));
                    nhanvien.setBirthday(rs.getString("birthday"));
                    nhanvien.setGender(rs.getString("gender"));
                    nhanvien.setGender(rs.getString("email"));
                    nhanvien.setGender(rs.getString("address"));
                    JOptionPane.showMessageDialog(this, "Id nhan vien là : " + rs.getString("id")
                            + "\nTên đầy đủ : " + rs.getString("fullname")
                            + "\nNgày sinh : " + rs.getString("birthday") + "\nGiới tính : " + rs.getString("gender")
                            + "\nEmail : " + rs.getString("email")
                            + "\nĐịa Chỉ : " + rs.getString("address"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jSearchActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
        if (!"admin".equals(textUser.getText())&& !"user1".equals(textUser.getText()) && !"user2".equals(textUser.getText())) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng username!!!");
        } else if (!"123456".equals(textPass.getText())) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng password!!!");
        } else if (jId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Id!!! ");
        } else if (jFullname.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Fullname!!! ");
        } else if (jAddress.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Address!!! ");
        } else if (jBirthday.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Birthday!!! ");
        } else if (jGender.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Gender!!! ");
        } else if (jEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Email!!! ");
        } else {
            try {
                Connection conn = learn.com.form.CSDL.getConnection();
//                String sql = "insert into tbnhanvien values (null,?,?,?,?,?,?)";
                String sql = "insert into tbnhanvien(id,fullname,birthday,gender,email,address)"+ "values (?,?,?,?,?,?)";
                java.sql.PreparedStatement stm = conn.prepareCall(sql);
                NhanVien nhanvien = new NhanVien();
                stm.setString(2, nhanvien.getFullname());
                stm.setString(3, nhanvien.getBirthday());
                stm.setString(4, nhanvien.getGender());
                stm.setString(5, nhanvien.getEmail());
                stm.setString(6, nhanvien.getAddress());
                stm.setString(1, nhanvien.getId());
                stm.executeUpdate();
                JOptionPane.showMessageDialog(this, "Thêm thành công ID" + nhanvien.getId());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jAddActionPerformed

    private void textPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JTextField jAddress;
    private javax.swing.JTextField jBirthday;
    private javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JButton jDellbtn;
    private javax.swing.JTextField jEmail;
    private javax.swing.JButton jFixbtn;
    private javax.swing.JTextField jFullname;
    private javax.swing.JTextField jGender;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jPassword;
    private javax.swing.JButton jSearch;
    public javax.swing.JButton jShowbtn;
    private javax.swing.JLabel jUsername;
    private javax.swing.JButton loginbtn;
    public javax.swing.JTextField textPass;
    public javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
